title: alston.id.au
description: "Lachlan Alston — IT technician, FOSS advocate, suckless enthusiast."
permalink: /posts/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

nav:
  - title: Home
    url: /
  - title: Posts
    url: /posts
  - title: Rocks
    url: /rocks
